spring.application.name=abha-integration
abdm.client.id=SBXID_045679
abdm.client.secret=6bee837a-d81b-4825-843b-08f1c64c4b7e

spring.datasource.url=jdbc:h2:mem:abha_hmis;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
